name: "SPIN! THAT! WHEEL!"

on:
  workflow_dispatch:

jobs:
  Spin:
    name: "Spin"
    runs-on: ["ubuntu-latest"]
    environment: "Spin"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Wheel Input
        id: get_input
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          .github/workflows/scripts/get-wheel-input.sh
      - name: Pick Prize
        shell: bash
        env:
          item_number: ${{ steps.get_input.outputs.item_number }}
        run: |
          prize=$(cat inventory.txt | head -n "${item_number}" | tail -n 1)
          echo "Chose ${prize} @ ${item_number}"
          sed -i "${item_number}d" "inventory.txt"
      - name: Save Inventory
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          add: "inventory.txt"
          author_name: "Matt Birum"
          committer_name: "Matt Birum"
          message: "Removing item from inventory"
          pull: '--ff'
