name: "SPIN! THAT! WHEEL!"

on:
  workflow_dispatch:

jobs:
  Start:
    name: "Start"
    runs-on: ["ubuntu-latest"]
    environment: "Wait For Spin"
    steps:
      - name: Wait
        shell: bash
        run: |
          echo "Waiting for wheel input..."

  Spin:
    name: "Spin"
    runs-on: ["ubuntu-latest"]
    needs: ["Start"]
    steps:
      - name: Get Wheel Input
        id: get_input
        shell: bash
        run: |
          ./.github/workflows/scripts/get-wheel-input.sh
      - name: Pick Prize
        shell: bash
        run: |
          echo "Picking prize..."
