name: "SPIN! THAT! WHEEL!"

on:
  workflow_dispatch:

jobs:
  Spin:
    name: "Spin"
    runs-on: ["ubuntu-latest"]
    environment: "Spin"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Get Wheel Input
        id: get_input
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          .github/workflows/scripts/get-wheel-input.sh
      - name: Pick Prize
        id: pick_prize
        shell: bash
        env:
          item_number: ${{ steps.get_input.outputs.item_number }}
        run: |
          inventory_count=$(cat inventory.txt | wc -l)
          if [ "$inventory_count" == "0" ]; then
            echo "Sorry! We're out of prizes ;'(  " >> $GITHUB_STEP_SUMMARY
            echo " " >> $GITHUB_STEP_SUMMARY
            echo "![](https://github.com/buymyrum/prize-wheel/blob/main/images/cat.png?raw=true)" >> $GITHUB_STEP_SUMMARY
          else
            prize=$(cat inventory.txt | head -n "${item_number}" | tail -n 1)
            prize_description=$(cat catalog.txt | grep "${prize}|" | cut -d'=' -f 1 | cut -d'|' -f 2)
            echo "#### You've won ${prize_description}!" >> $GITHUB_STEP_SUMMARY
            image_url="https://github.com/buymyrum/prize-wheel/blob/main/images/${prize}.png?raw=true"
            image_markdown="![](${image_url})"
            echo "$image_markdown" >> $GITHUB_STEP_SUMMARY
            echo "prize=${prize}" >> $GITHUB_OUTPUT
            sed -i "${item_number}d" "inventory.txt"
          fi
      - name: Save Inventory
        uses: EndBug/add-and-commit@v9
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          add: "inventory.txt"
          author_name: "Matt Birum"
          committer_name: "Matt Birum"
          message: "Removing ${{ steps.pick_prize.outputs.prize }} from inventory"
          pull: '--ff'
      - name: Start Next Wheel Spin
        if: ${{ always() }}
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh workflow run "SPIN! THAT! WHEEL!"
